# AD9767 on AX_7035 J9

set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[0]}]
set_property PACKAGE_PIN D16 [get_ports {da_data1[13]}]
set_property PACKAGE_PIN E16 [get_ports {da_data1[12]}]
set_property PACKAGE_PIN F14 [get_ports {da_data1[11]}]
set_property PACKAGE_PIN F13 [get_ports {da_data1[10]}]
set_property PACKAGE_PIN E14 [get_ports {da_data1[9]}]
set_property PACKAGE_PIN E13 [get_ports {da_data1[8]}]
set_property PACKAGE_PIN D15 [get_ports {da_data1[7]}]
set_property PACKAGE_PIN D14 [get_ports {da_data1[6]}]
set_property PACKAGE_PIN B13 [get_ports {da_data1[5]}]
set_property PACKAGE_PIN C13 [get_ports {da_data1[4]}]
set_property PACKAGE_PIN A14 [get_ports {da_data1[3]}]
set_property PACKAGE_PIN A13 [get_ports {da_data1[2]}]
set_property PACKAGE_PIN C15 [get_ports {da_data1[1]}]
set_property PACKAGE_PIN C14 [get_ports {da_data1[0]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[0]}]
# set_property PACKAGE_PIN B18 [get_ports {da_data2[13]}]
# set_property PACKAGE_PIN B17 [get_ports {da_data2[12]}]
# set_property PACKAGE_PIN A19 [get_ports {da_data2[11]}]
# set_property PACKAGE_PIN A18 [get_ports {da_data2[10]}]
# set_property PACKAGE_PIN C19 [get_ports {da_data2[9]}]
# set_property PACKAGE_PIN C18 [get_ports {da_data2[8]}]
# set_property PACKAGE_PIN A20 [get_ports {da_data2[7]}]
# set_property PACKAGE_PIN B20 [get_ports {da_data2[6]}]
# set_property PACKAGE_PIN C17 [get_ports {da_data2[5]}]
# set_property PACKAGE_PIN D17 [get_ports {da_data2[4]}]
# set_property PACKAGE_PIN D19 [get_ports {da_data2[3]}]
# set_property PACKAGE_PIN E19 [get_ports {da_data2[2]}]
# set_property PACKAGE_PIN E18 [get_ports {da_data2[1]}]
# set_property PACKAGE_PIN F18 [get_ports {da_data2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports da_clk1]
# set_property IOSTANDARD LVCMOS33 [get_ports da_clk2]
set_property IOSTANDARD LVCMOS33 [get_ports da_wrt1]
# set_property IOSTANDARD LVCMOS33 [get_ports da_wrt2]
set_property PACKAGE_PIN A15 [get_ports da_clk1]
# set_property PACKAGE_PIN B16 [get_ports da_clk2]
set_property PACKAGE_PIN A16 [get_ports da_wrt1]
# set_property PACKAGE_PIN B15 [get_ports da_wrt2]
