set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property PACKAGE_PIN M13 [get_ports sys_rst_n]
set_property PACKAGE_PIN G15 [get_ports uart_rxd]
# set_property PACKAGE_PIN G16 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
# set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
